services:
  - type: web_service
    name: prompt-refinement-backend
    env: node
    region: oregon
    plan: free
    repo: modsus-shashank/Multi-Modal-Prompt-Refinement-System
    branch: master
    root: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

  - type: static_site
    name: prompt-refinement-frontend
    env: static
    region: oregon
    plan: free
    repo: modsus-shashank/Multi-Modal-Prompt-Refinement-System
    branch: master
    root: frontend
    buildCommand: npm ci && npm run build
    publishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://multi-modal-prompt-refinement-system-ni9a.onrender.com
